version: '3.7'

services:

   db:
      build:
         context: .
         dockerfile: ./Dockerfile_db
      container_name: mariadb

   app:
      build:
         context: .
         dockerfile: ./Dockerfile_app
      container_name: ttccpp
